= Supporto risposta Tracker
:allow-uri-read: 




=== Supporto risposta Tracker

Tracker ora fornisce le risposte API in modo da poter vedere l'output dell'API REST relativo all'attività.



=== Supporto di autenticazione link per AWS Secrets Manager

Ora puoi utilizzare i segreti di AWS Secrets Manager per autenticare i link in modo da non dover utilizzare le credenziali archiviate nei workload di BlueXP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connettersi a un file system FSX per ONTAP con un collegamento Lambda"]



=== Implementare le Best practice per un file system FSX per ONTAP

I carichi di lavoro BlueXP  fornisce una dashboard in cui puoi esaminare lo stato con l'architettura ideale delle configurazioni del file system. Puoi sfruttare questa analisi per implementare le Best practice per i file system FSX per ONTAP. L'analisi della configurazione del file system include le seguenti configurazioni: Soglia di capacità SSD, snapshot locali pianificate, backup FSX for ONTAP pianificati, tiering dei dati e replica dei dati remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Scopri l'analisi con un'architettura ideale per le configurazioni del file system"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implementare le Best practice per i file system"]




=== Notifica con un'architettura ottimale per i problemi del file system

Nella console BlueXP , i file system FSX per ONTAP con problemi ben strutturati ora visualizzano una notifica in Canvas che indica quando i file system hanno problemi da risolvere.



=== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente di fabbrica del carico di lavoro e la documentazione ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura-scrittura" per fare riferimento all'automazione delle autorizzazioni.
