---
sidebar: sidebar 
permalink: use/task-manage-fsx-volumes.html 
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone 
summary: Con BlueXP puoi gestire volumi, cloni e snapshot e modificare i criteri di tiering per FSX per ONTAP. 
---
= Gestire i volumi per Amazon FSX per NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare e gestire volumi, cloni e snapshot e modificare i criteri di tiering per FSX per ONTAP utilizzando BlueXP.



== Visualizzare i dettagli del volume

Dopo aver creato un volume, è possibile visualizzare i dettagli della configurazione.

. Aprire l'ambiente di lavoro.
+

NOTE: È possibile passare il mouse sul nome del volume per visualizzare il tipo di volume.

. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Volume Actions* (azioni volume).
. Selezionare *Visualizza dettagli volume*.




== Modificare i volumi

Dopo aver creato un volume, è possibile modificarlo in qualsiasi momento.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Volume Actions* (azioni volume).
. Selezionare *Edit volume settings* (Modifica impostazioni volume).
. Selezionare *Applica*.




== Clonare i volumi

Dopo aver creato un volume, è possibile creare un nuovo volume di lettura/scrittura da un nuovo Snapshot.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Volume Actions* (azioni volume).
. Selezionare *Clone the volume*.
. Immettere un nome per il volume clonato.
. Selezionare *Clone*.




== Gestire i tag di volume

È possibile aggiungere, modificare o eliminare tag di volume. I tag aggiunti in BlueXP vengono riflessi nella console AWS. La sincronizzazione dei tag con la console AWS può richiedere fino a un'ora.


NOTE: Non è possibile modificare i tag di volume creati in BlueXP fino a quando non vengono sincronizzati con AWS. Questa operazione può richiedere fino a un'ora. Se l'opzione *Manage volume tags* (Gestisci tag volume) non è attiva, AWS non ha ancora sincronizzato i tag del volume.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Volume Actions* (azioni volume).
. Selezionare *Manage volume tags* (Gestisci tag volume).
. Selezionare *Save* (Salva) per applicare le modifiche.




== Gestire le copie Snapshot

Le copie Snapshot forniscono una copia point-in-time del volume. Creare copie Snapshot e ripristinare i dati in un nuovo volume.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Protection Actions* (azioni di protezione).
. Selezionare una delle opzioni disponibili per gestire le copie Snapshot:
+
** *Creare una copia Snapshot*
** *Ripristina da una copia Snapshot*


. Seguire le istruzioni per completare l'azione selezionata.




== Modificare la policy di tiering

Modificare la policy di tiering per il volume.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Advanced Actions* (azioni avanzate).
. Selezionare *Cambia policy di tiering*.
. Selezionare un nuovo criterio di tiering dei volumi e fare clic su *Change* (Modifica).




== Eliminare i volumi

Eliminare i volumi non più necessari.

.Prima di iniziare
Non è possibile eliminare un volume che faceva parte di una relazione SnapMirror utilizzando BlueXP. I volumi SnapMirror devono essere cancellati utilizzando AWS Management Console o CLI.

.Fasi
. Aprire l'ambiente di lavoro.
. Aprire la scheda del volume e selezionare *Manage Volume* (Gestisci volume) per aprire il menu *Volume Actions* (azioni volume).
. Selezionare *Delete the volume* (Elimina volume).
. Inserire il nome dell'ambiente di lavoro e confermare che si desidera eliminare il volume. La rimozione completa del volume da BlueXP può richiedere fino a un'ora.



NOTE: Se si tenta di eliminare un volume clonato, viene visualizzato un errore.
